#TestConfig.
configversion : 1.0
#Give pickaxe experience if the block is placed by a player (if true, can lead to duplication if silk-touch give exp aswell)
playerplacedblockgive-exp : false
silktouchgive-exp : true
#Default on the server, players can change it via command settings
XPactionbar : true
XPSound : true
LevelUpSound : true
#Cost for every level of enchantements.
efficost: "3,5,7,9,13"
unbreakcost: "1,4,7"
fortunecost: "5,8,12"
mendingcost: 21
silktouchcost : 18