name: ToolsPlus
version: '${project.version}'
main: fr.infinitystudios.toolsplus.ToolsPlus
api-version: 1.19
authors: [ HyPeRXKo ]
description: Evolutive tools system with levels and custom display
website: https://vlxproject.fr
commands:
  ToolsPlus:
    description: Main command
    usage: /<command>
    aliases: tlps
